vfs: fix include on musl
On musl, this fails to compile due to -Werror=cpp:

  CC       src/vfs.lo
In file included from src/vfs.c:6:
/usr/include/sys/fcntl.h:1:2: error: #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h> [-Werror=cpp]
    1 | #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h>
      |  ^~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:1314: src/vfs.lo] Error 1

Signed-off-by: Cameron Nemo <cam@nohom.org>